name: Frontend CI

on:
  push:
    branches: [ "dev", "main" ]
    paths:
      - "frontend/acadex_frontend/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "frontend/acadex_frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/acadex_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build